version: '3.9'

services:
  app:
    image: fastapi_template:${VERSION}
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_template
    restart: unless-stopped
    ports:
      - "8000:80"
